Repository Seagate/cortx-re, pull requests merged in 2022-11, with the labels that each got.

#1256 CORTX-34324: Add Support for Dashboard application container image generation
  solutions/dashboard/build/build.sh
  solutions/dashboard/build/dashboard-images.groovy
  solutions/dashboard/build/docker-compose.yml
  solutions/dashboard/deployment/dashboard/codacy.yaml
  solutions/dashboard/deployment/dashboard/portscanner.yaml
Labels: cla-signed, dashboard

#1255 CORTX-34348: Add cortx-motr-apps in build
  scripts/release_support/set-local-repo.sh
  solutions/cortx-motr-apps/jenkins/deploy-motr-apps.groovy
  solutions/cortx-motr-apps/scripts/deploy-motr-apps.sh
Labels: cla-signed

#1257 CORTX-34342: Removed schedule from utils PR pipeline
  jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
Labels: cla-signed

#1254 CORTX-34324: Modified Codacy script and Logstash ConfigMap
  solutions/dashboard/config/logstash/LogstashConfigmap.yaml
  solutions/dashboard/tools/codacy/issues.py
  solutions/dashboard/tools/codacy/main.py
  solutions/dashboard/tools/codacy/repositories.py
Labels: cla-signed, dashboard

#1259 CORTX-34365: Added Jenkins details in the documentation
  docker/jenkins/README.md
  docker/jenkins/jenkins_arch.png
Labels: cla-signed

#1246 CORTX-34332: Remove parameters causing build failures from Jenkinsfile and update OS name
  jenkins/deployment/community/cortx-community-deploy.groovy
Labels: cla-signed

#1262 CORTX-34351: Modified YAML files of dashboard deployment
  solutions/dashboard/deployment/dashboard/dashboardconfigmap.yaml
  solutions/dashboard/deployment/dashboard/logstash.yaml
Labels: cla-signed

#1264 CORTX-34379: Support for GitHub collector image generation
  solutions/dashboard/build/build.sh
  solutions/dashboard/build/dashboard-images.groovy
  solutions/dashboard/build/docker-compose.yml
  solutions/dashboard/deployment/dashboard/dashboard-secret.yaml
  solutions/dashboard/deployment/dashboard/github.yaml
Labels: cla-signed, dashboard

#1263 CORTX-34368: Fix for the cortx-re codacy issues to test dashboard
  jenkins/automation/alex.groovy
  jenkins/deployment/factory_deployment/factory_field_deployment.groovy
  jenkins/internal-ci/generic/branch/cortx-py-utils.groovy
  jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
Labels: cla-signed

#1265 CORTX-34377: Dashboard Application Deployment
  solutions/dashboard/deployment/README.md
  solutions/dashboard/deployment/dashboard/dashboard-secret.yaml
  solutions/dashboard/deployment/dashboard/portscanner.yaml
  solutions/dashboard/deployment/dashboard/portscannercrd.yaml
  solutions/dashboard/deployment/elasticsearch/elastic-user.yaml
Labels: dashboard
