Repository Seagate/cortx-re, pull requests merged in 2022-08, with the labels that each got.

#1159 CORTX-33693 Fix Hare build failures
  jenkins/internal-ci/generic/branch/cortx-py-utils.groovy
  jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy
  jenkins/internal-ci/generic/branch/csm-agent.groovy
  jenkins/internal-ci/generic/branch/hare.groovy
  jenkins/internal-ci/generic/branch/motr.groovy
  jenkins/internal-ci/generic/branch/provisioner.groovy
Labels: cla-signed

#1160 CORTX-33695 - Add performance stats in perfornace-ci
  jenkins/performance-ci/nightly-performance-ci.groovy
  scripts/performance/_run-performace-tests-functions.sh
  scripts/performance/run-performace-tests.sh
Labels: cla-signed

#1154 CORTX-32704: Minor Changes and added Tested By for Community Build deployment
  solutions/community-deploy/CORTX-Deployment.md
Labels: cla-signed

#1161 CORTX-32962 : Update community build script for tag support
  solutions/community-deploy/CORTX-Deployment.md
  solutions/community-deploy/build-cortx.sh
  solutions/community-deploy/cloud/AWS/README.md
Labels: cla-signed

#1164 CORTX-33695 - Performance CI email notification and message improvements
  jenkins/internal-ci/generic/nightly/nightly-performance-ci.groovy
  scripts/performance/_run-performace-tests-functions.sh
Labels: cla-signed

#1166 CORTX-33837 - Disable wait for downstream 1N and 3N deployment jobs in Release pipeline
  jenkins/internal-ci/generic/branch/release.groovy
Labels: cla-signed

#1167 CORTX-33837 Performance-CI improvements
  jenkins/internal-ci/generic/nightly/nightly-performance-ci.groovy
  scripts/performance/_run-performace-tests-functions.sh
Labels: cla-signed

#1169 CORTX-33862 Integrate SpLint tool to detect Memory leaks Motr Repo
  jenkins/automation/splint-memory-leak.groovy
Labels: cla-signed, Status: Waiting to be Reviewed

#1168 CORTX-33805 - Added local registry support
  docker/cortx-deploy/build.sh
  jenkins/deployment/community/cortx-community-deploy.groovy
  solutions/community-deploy/build-cortx.sh
Labels: cla-signed

#1165 CORTX-33872: RGW: Adding versioning & tagging test cases to nightly s3-tests ceph & splunk test suite job
  scripts/automation/s3-test/ceph/s3_v2_tests.txt
  scripts/automation/s3-test/ceph/s3_v4_tests.txt
  scripts/automation/s3-test/splunk/s3_v2_tests.txt
  scripts/automation/s3-test/splunk/s3_v4_tests.txt
Labels: cla-signed, Status: Waiting to be Reviewed

#1171 CORTX-32963: Automate GitHub Release creation
  jenkins/automation/commit-tag.groovy
  jenkins/release-process/github-release.groovy
  jenkins/release-process/release-process.groovy
  scripts/release_support/changelog.sh
  scripts/release_support/create-cortx-github-release.sh
Labels: cla-signed

#1173 CORTX-33818 Updated Kubernetes metrics server and dashboard deployment pipeline
  jenkins/automation/kubernetes/setup-metrics-server.groovy
  solutions/kubernetes/cluster-functions.sh
  solutions/kubernetes/metrics-server/setup-metrics-server-functions.sh
  solutions/kubernetes/metrics-server/setup-metrics-server.sh
Labels: cla-signed

#1156 CORTX-32909: Instructions to build cortx images on AWS (Multi-node) setup with Terraform
  solutions/community-deploy/build-cortx.sh
  solutions/community-deploy/cloud/AWS/README.md
  solutions/community-deploy/cloud/AWS/main.tf
  solutions/community-deploy/cloud/AWS/setup.sh
  solutions/community-deploy/cloud/AWS/tool_setup.sh
  solutions/community-deploy/cloud/AWS/user.tfvars
  solutions/community-deploy/cloud/AWS/variable.tf
  solutions/kubernetes/cluster-setup.sh
Labels: community

#1170 CORTX-32909: Update minor CORTX-Deployment.md Instructions with locally generated images support
  solutions/community-deploy/CORTX-Deployment.md
Labels: cla-signed, community

#1174 CORTX-32899: New jenkins job to install and run predefined workloads
  jenkins/performance-ci/perfline-workloads.groovy
  scripts/performance/cortx-perfline.sh
  scripts/performance/install-perfline.sh
Labels: cla-signed

#1175 CORTX-33942 - Add support for K8s Services v0.10.0
  scripts/performance/cortx-perfline.sh
  solutions/community-deploy/CORTX-Deployment.md
  solutions/kubernetes/cortx-deploy.sh
Labels: cla-signed

#1178 CORTX-33975 remove multipart tests from sanity
  solutions/kubernetes/io-sanity.sh
Labels: cla-signed

#1176 CORTX-33942: Improve GitHash fetch in changelog generation script
  scripts/release_support/changelog.sh
Labels: cla-signed

#1181 CORTX-34001: Fix logic to fetch image id for GitHub release
  scripts/release_support/create-cortx-github-release.sh
Labels: cla-signed

#1182 CORTX-34007 Use v0.9.0 as default Services version
  scripts/performance/cortx-perfline.sh
  solutions/community-deploy/CORTX-Deployment.md
  solutions/kubernetes/cortx-deploy.sh
Labels: cla-signed

#1183 CORTX-33975 Enable multipart tests in sanity
  solutions/kubernetes/io-sanity.sh
Labels: cla-signed

#1185 CORTX-33977 Adapting Newly tuned Resource limit values in RE Deployment Job
  solutions/kubernetes/cortx-deploy-functions.sh
Labels: cla-signed

#1180 CORTX-33117 : Adding copy-object API test cases to nightly s3-tests ceph & splunk test suite job
  scripts/automation/s3-test/ceph/s3_v2_tests.txt
  scripts/automation/s3-test/ceph/s3_v4_tests.txt
  scripts/automation/s3-test/splunk/s3_v2_tests.txt
  scripts/automation/s3-test/splunk/s3_v4_tests.txt
Labels: cla-signed

#1186 CORTX-34020: Alex allow words to ignore alex scan
  .alexrc
Labels: cla-signed

#1189 CORTX-33863: Add PR based splint checker pipeline
  jenkins/automation/splint-memory-leak-pr.groovy
Labels: cla-signed

#1071 CORTX-31948:Removal of un-used rpms and python pacakges from CSM.
  docker/cortx-deploy/python_requirements.txt
Labels: cla-signed, cortx-third-party, Status: Waiting to be Reviewed

#1192 CORTX-33968: Add GitHub Action pr-title-checker
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-checker.yml
Labels: cla-signed

#1184 CORTX-33942: Add support for Service Release v0.11.0
  scripts/performance/cortx-perfline.sh
  solutions/community-deploy/CORTX-Deployment.md
  solutions/kubernetes/cortx-deploy.sh
Labels: cla-signed

#1199 CORTX-34078: Install xmlstarlet for cortx-rgw build process
  jenkins/custom-ci/generic/cortx-rgw.groovy
  jenkins/custom-ci/generic/custom-ci.groovy
  jenkins/custom-ci/generic/motr.groovy
  solutions/kubernetes/ceph-binary-build.sh
Labels: cla-signed

#1187 CORTX-32167: CI for cortx-cc component
  jenkins/custom-ci/generic/cortx-cc.groovy
  jenkins/custom-ci/generic/custom-ci.groovy
  jenkins/custom-ci/generic/motr.groovy
  jenkins/internal-ci/generic/branch/cortx-cc.groovy
Labels: cla-signed

#1204 CORTX-32167: Fix broken links in custom-ci
  jenkins/custom-ci/generic/custom-ci.groovy
Labels: cla-signed
