Repository Seagate/cortx-re, pull requests merged in 2022-10, with the labels that each got.

#1244 COMMUNITY: Script to download assets from release and setup local yum repository
  scripts/release_support/set-local-repo-iso.sh
  scripts/release_support/set-local-repo.sh
Labels: cla-signed

#1245 CORTX-34339: cortx-rgw build is failing with latest main branch
  solutions/kubernetes/ceph-binary-build.sh
Labels: cla-signed, Check Failed - Invalid PR Title Prefix

#1248 CORTX-34330: Nightly Build Issues
  jenkins/automation/kubernetes/setup-cortx-cluster.groovy
  jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
Labels: cla-signed

#1250 CORTX-34324: Codacy script modified and Cronjob added
  solutions/dashboard/config/codacy/CodacyCronjob.yaml
  solutions/dashboard/tools/codacy/main.py
  solutions/dashboard/tools/codacy/mongodb.py
Labels: dashboard

#1252 CORTX-34342: Disabled schedule from nightly-perfline-perf
  jenkins/internal-ci/generic/nightly/nightly-perfline-performance.groovy
Labels: cla-signed

#1251 COMMUNITY: Add support for Codacy in Argo CD based deploymet
  solutions/dashboard/deployment/README.md
  solutions/dashboard/deployment/dashboard/codacy.yaml
  solutions/dashboard/deployment/dashboard/dashboard-secret.yaml
  solutions/dashboard/deployment/elasticsearch/crds.yaml
  solutions/dashboard/deployment/elasticsearch/elastic-namespace.yaml
  solutions/dashboard/deployment/elasticsearch/elastic-user.yaml
  solutions/dashboard/deployment/elasticsearch/elasticsearch.yaml
  solutions/dashboard/deployment/elasticsearch/kibana.yaml
  solutions/dashboard/deployment/elasticsearch/local-path-provisioner.yaml
  solutions/dashboard/deployment/elasticsearch/operator.yaml
Labels: cla-signed, dashboard

#1253 CORTX-34342: Update nightly deploy email notification recipients and Reduce frequency for CORTX Build Image Pipeline
  jenkins/automation/docker-image-ci.groovy
  jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
Labels: needs-attention, cla-signed
