Repository Seagate/cortx-re, pull requests merged in 2023-02, with the labels that each got.

#1283 CORTX-34403: Update Jenkins image and volumes
  docker/jenkins/prod_jenkins/docker-compose.yaml
Labels: cla-signed, vmware

#1284 CORTX-34414: Fix issue with Motr Ubuntu based build
  jenkins/internal-ci/generic/branch/motr.groovy
Labels: cla-signed

#1295 CORTX-34425: Add support for logstash image generation
  solutions/dashboard/build/build.sh
  solutions/dashboard/build/docker-compose.yml
  solutions/dashboard/build/logstash/Dockerfile
  solutions/dashboard/build/logstash/Readme.md
  solutions/dashboard/charts/dashboard-project/values.yaml
  solutions/dashboard/config/logstash/LogstashCronjob.yaml
  solutions/dashboard/deployment/dashboard/logstash.yaml
Labels: cla-signed, dashboard

#1297 CORTX-34459: Alex script modification
  scripts/automation/alex/alex.py
Labels: cla-signed
